#- platform: workday
#  country: 'NO'
#  name: workday

#- platform: workday
#  country: 'NO'
#  name: school_night_sensor
#  days_offset: 1
#  country: 'NO' 

- platform: bayesian
  prior: 0.63
  name: Trym Presence
  probability_threshold: 0.8
  device_class: presence
  observations:
  - entity_id: 'device_tracker.tryms_iphone_11_wifi'
    prob_given_true: 0.9
    prob_given_false: 0.4 # Tryms WiFi disconnecter ofte
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.tryms_iphone_app'
    prob_given_true: 0.9
#    prob_given_false: 0.8 # Tryms GPS er upålitelig når han er på tur
    prob_given_false: 0.4 # Test -
    platform: 'state'
    to_state: 'home'

- platform: 'bayesian'
  name: 'Jeanette Presence'
  prior: 0.63
  probability_threshold: 0.9
  device_class: presence
  observations:
  - entity_id: 'device_tracker.jeanette'
    prob_given_true: 0.9
    prob_given_false: 0.0
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.jeanette_gps'
    prob_given_true: 0.9
    prob_given_false: 0.1 # Jeanette har på mobildata, og GPSen er pålitelig
    platform: 'state'
    to_state: 'home'

- platform: bayesian
  prior: 0.63
  name: Tarald Presence
  probability_threshold: 0.9
  device_class: presence
  observations:
  - entity_id: 'device_tracker.das_ifon_wifi'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'
  - entity_id: 'device_tracker.das_ifon_app'
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'


#- platform: template
#  sensors:
#    tracktest_tuva:
#      value_template: >
#          {{ is_state('device_tracker.tuva','home') or is_state('device_tracker.tuva_gps','home') }}
#      device_class: 'presence'
#      attribute_templates:
#        latitude: >
#          {% if is_state('device_tracker.tuva','home') %}
#            {{ state_attr('zone.home','latitude') }}
#          {% else %}
#            {{ state_attr('device_tracker.tuva_gps','latitude') }}
#          {% endif %}
#        longitude: >
#          {% if is_state('device_tracker.tuva','home') %}
#            {{ state_attr('zone.home','longitude') }}
#          {% else %}
#            {{ state_attr('device_tracker.tuva_gps','longitude') }}
#          {% endif %}
