# Custom Samsung TV Config
- platform: samsungtv_tizen
  host: 192.168.1.210
  port: 8002
  # Wired MAC
  #mac: 5c:49:7d:d1:b0:83
  # WiFi MAC
  mac: c0:97:27:4d:7e:78
  name: 'Das TV'
  update_method: smartthings
  app_list: '{"Netflix": "11101200001/org.tizen.netflix-app", "Prime Video": "3201512006785/org.tizen.ignition", "YouTube": "111299001912", "Plex": "3201512006963", "Internet": "org.tizen.browser", "HBO GO": "3201706012478"}'
  api_key: !secret smartthings_token
  device_id: !secret samsung_tv_device_id

# Nvidia Shield Pro. Use the Python ADB implementation, See https://selfhostedhome.com/integrating-nvidia-shield-with-home-assistant/
#- platform: androidtv
#  name: Shield Pro
#  host: 192.168.1.212
